<link href="<?php echo $this->basePath(); ?>/css/question.css?<?php echo substr(md5(microtime()),rand(0,26),5);?>" rel="stylesheet" type="text/css"/>
<?php 
if ($this->success != '') { ?>
    <div style="color: red;text-align: center;width: 100%;padding-top: 20px;">
        <h3><?php echo $this->success; ?></h3>
    </div>
    <?php
} else {
    if (isset($this->message) && $this->message != '') {
        ?>
        <div style="color: red;text-align: center;width: 100%;padding-top: 20px;">
            <h3><?php echo $this->message; ?></h3>
        </div>
        <?php
    }
}

$session = new \Zend\Session\Container('base');
if ($session->offsetExists('user')) {
    $identity = $session->offsetGet('user');
    $user_id = $identity['id'];
}


$model = new \Application\Model\Table('');
$select = new \Zend\Db\Sql\Select();
$select->from('user_exam')->where("user_id=".$user_id)->order('exam_date DESC')->limit(1);
$row = $model->selectWith($select)->toArray();
if (is_array($row) && count($row) > 0 && (!isset($this->showFormNganhNgheCapBac) || $this->showFormNganhNgheCapBac == FALSE)) {
    ?>
    <div class="row-fluid">
        <div class="span12">
            <div class="span4" style="margin-top: 20px;">
                <a class="download-result" href="<?php echo $this->basePath('/thi/viewresult'); ?>">
                    <button style="border-radius: 5px;background-color: brown;color: white;">
                        Xem kết quả lần thi gần nhất
                    </button>
                </a>
            </div>
        </div>
    </div>
    <?php
}
if (isset($this->showFormNganhNgheCapBac) && $this->showFormNganhNgheCapBac == true) { 
    echo $this->partial('application/thi/partial/form_nganhnghe_capbac.phtml');
}
?>
<div class="row-fluid">
    <div class="span12"></div>
</div>
<?php 
if (is_array($this->questions) && count($this->questions) > 0) {
    echo $this->partial('application/thi/partial/form_question.phtml');
}
?>
<script src="<?php echo $this->basePath();?>/js/jquery.fileDownload.js?<?php echo substr(md5(microtime()),rand(0,26),5);?>" type="text/javascript"></script>
<script type="text/javascript"> 
    jQuery(function ($){

        $(document).on("click", "a.download-result", function () {
            $.fileDownload($(this).prop('href'), {
                preparingMessageHtml: "Hệ thống đang download, vui lòng chờ cho đến khi hoàn thành.",
                failMessageHtml: "Đường truyền internet bị lỗi. Vui lòng thử lại sau."
            });
            return false; 
        });
    });
    
    
</script>