<?php
$items = $this->items;



$session = new \Zend\Session\Container('base');
if ($session->offsetExists('user')) {
    $identity = $session->offsetGet('user');
}


if (isset($this->message)&&trim($this->message)!='') {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3"></div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $this->message;
            ?>
        </div>
        <div class="span3"></div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="padding-top:20px;">
    <div class="span12">
        <?php     
//        $buttons[]=array('onclick'=>"window.location = '".$this->basePath('/admin/nganhnghe/add/')."'",'label'=>'Thêm ngành nghề');
//        echo $this->toolbar($buttons);
        ?>
        <div class="span12" style="margin-bottom: 20px;text-align: right;">
            <input onclick="window.location = '<?php echo $this->basePath();?>/admin/nganhnghe/add'" type="button" value="Thêm ngành nghề" class="button">          
        </div>
    </div>
</div>
<?php if (count($items) > 0) { ?>
    <form id="form1" method="post" action="<?php echo $this->url(); ?>">
        <?php
    }
    ?>
    <div class="row-fluid">

        <?php
        
        foreach ($items as $item) {


         
            ?>

            <div class="row-fluid item" id="<?php echo $item['id']; ?>">

                <div class="span10"><strong>
                        <?php echo $item['title']; ?></strong>
                </div>


                <div class="span2">
                    <a class="remove" title="Click vào đây để xóa" href="<?php echo $this->basePath('/admin/nganhnghe/delete/id/') . $item['id']; ?>">
                        <img class="delete question" src="<?php echo $this->basePath("/images/icon/delete-icon.png"); ?>"/>                                                   
                    </a>
                    <a title="Click vào đây để sửa" href="<?php echo $this->basePath('/admin/nganhnghe/edit/id/') . $item['id']; ?>">
                        <img style="width: 48px;height: 48px;cursor: pointer;" src="<?php echo $this->basePath("/images/icon/ico_edit.png"); ?>" onclick="editItem(this);"/>                                                   
                    </a>
                </div>

            </div>




            <?php
        }
        ?>

    </div>



