<script type="text/javascript" src="<?php echo $this->basePath(); ?>/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    jQuery(function ($) {
        CKEDITOR.replace('editor1', {
            language: 'en',
            filebrowserUploadUrl: '/upload.php'
        });
    });

</script>
<?php

if (isset($this->message)&&trim($this->message)!='') {
    ?>
    <div style="color: red;text-align: center;width: 100%;">
        <h3><?php echo $this->message; ?></h3>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 20px;margin-bottom: 20px;">
    <?php     
    $buttons[]=array('onclick'=>'document.form.submit();','label'=>'Lưu');
    echo $this->toolbar($buttons);
    ?>
</div>
<div class="row-fluid">
    <div class="span12">
        <form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->basePath('/admin/homecontent/save'); ?>" method="post">
            <div class="row-fluid" style="margin-top: 10px;">

                <div class="span12">
                    <textarea rows="" cols="" name="content" id="editor1"><?php echo $this->content; ?></textarea>
                </div>
            </div>
        </form>
    </div>
</div>

