<?php 
$bg = $this->bg;
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span12" style="text-align: center;font-size: 30px;">Hình nền trang chủ</div>    
</div>
<div class="row-fluid">
    <div class="span5"></div>
    <div class="span7">
            <div class="row-fluid">
                <div class="span12">
                    <?php
                    if ($bg['bg'] != "") {
                        
                        Core_Common_Image::echoImage($this->basePath($bg['bg']), 70, 70, 'height');
                    } else {
                        ?>
                        <img alt="" src="<?php echo $this->basePath('/images/img_photo01.jpg'); ?>">
                        <?php
                    }
                    ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <p>                                            
                        <input type="file" name="bg" onchange='allowUpload(this);' accept="image/*"/>
                    </p>                
                </div>
            </div>

    </div>

</div>
