<?php 
$logo = $this->logo;
?>
<div class="row-fluid" style="margin-top: 10px;">
    <div class="span12" style="text-align: center;font-size: 30px;">Logo</div>    
</div>
<div class="row-fluid">
    <div class="span5"></div>
    <div class="span7">
            <div class="row-fluid">
                <div class="span12">
                    <?php
                    if ($logo['file_name'] != "") {
                        
                        Core_Common_Image::echoImage($this->baseUrl($logo['file_name']), 70, 70, 'height');
                    } else {
                        ?>
                        <img alt="" src="<?php echo $this->baseUrl('/images/img_photo01.jpg'); ?>">
                        <?php
                    }
                    ?>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span12">
                    <p>                                            
                        <input type="file" name="logo" onchange='allowUpload(this);' accept="image/*"/>
                    </p>                
                </div>
            </div>
            <div class="row-fluid">
                <div class="span4">
                    <div class="row-fluid">
                        <div class="span2">
                            <input type="radio" value="1" name="dynamic" id="dynamic"<?php if ($logo['dynamic'] == '1') echo ' checked'; ?>/>
                        </div>
                        <div class="span10">
                            <label for="dynamic">Chuyển động</label>
                        </div>


                    </div>

                </div>
                <div class="span8">
                    <div class="row-fluid">
                        <div class="span1">
                            <input type="radio" value="0" name="dynamic" id="static"<?php if ($logo['dynamic'] == '0') echo ' checked'; ?>/>
                        </div>
                        <div class="span11">
                            <label for="static">Đứng yên</label>
                        </div>


                    </div>

                </div>
            </div>

        
    </div>

</div>