<script type="text/javascript" src="<?php echo $this->basePath(); ?>/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
    jQuery(function ($) {
        CKEDITOR.replace('editor1', {
            language: 'en',
            filebrowserUploadUrl: '/upload.php'
        });
    });

</script>

<div class="row-fluid">
    <div class="span12">

        <div class="row-fluid" style="margin-top: 10px;">

            <div class="span12">
                <textarea rows="" cols="" name="footer_text" id="editor1"><?php echo $this->footer_text; ?></textarea>
            </div>

        </div>

    </div>
</div>


