<?php 
$session = new \Zend\Session\Container('base');
if ($session->offsetExists('user')) {
    $identity = $session->offsetGet('user');
    $user_id = $identity['id'];
}

$model = new \Application\Model\Table('');
$select = new \Zend\Db\Sql\Select();
$select->from('user_exam')->where("user_id=" . $user_id)->order("exam_date DESC")->limit(1);
$row = $model->selectWith($select)->toArray();
$nganhNghes = $this->nganhNghes;
?>
<form method="POST" id="form1" onsubmit="return false;">
    <div class="row-fluid">
        <div class="span12">
            <div style="margin-top: 20px;" class="span3">
                <?php 
                if (is_array($row) && count($row) > 0) { ?>
                    <a class="download-result" href="<?php echo $this->basePath('/thi/viewresult'); ?>">
                        <button style="border-radius: 5px;background-color: brown;color: white;">
                            Xem kết quả lần thi gần nhất
                        </button>
                    </a>
                    <?php
                }
                ?>
                
            </div>

            <div class="span4" style="margin-top: 20px;">
                <select id="nganh_nghe_id" name="nganh_nghe_id" style="width: 100%;">
                    <option value="0">------------------Chọn ngành nghề------------------</option>
                    <?php foreach ($nganhNghes as $nganhNghe) { ?>
                        <option value="<?php echo $nganhNghe['id']; ?>"><?php echo $nganhNghe['title']; ?></option>
                        <?php
                    }
                    ?>
                </select>
            </div>
            <div class="span3" style="margin-top: 20px;">
                <select id="level" name="level" style="width: 100%;">
                    <option value="0">-----------Chọn cấp bậc-----------</option>
                    <option value="<?php echo \Application\Model\Question::BAC1; ?>">Bậc 1</option>
                    <option value="<?php echo \Application\Model\Question::BAC2; ?>">Bậc 2</option>
                    <option value="<?php echo \Application\Model\Question::BAC3; ?>">Bậc 3</option>
                    <option value="<?php echo \Application\Model\Question::BAC4; ?>">Bậc 4</option>
                    <option value="<?php echo \Application\Model\Question::BAC5; ?>">Bậc 5</option>
                </select>
            </div>
            <!--<div class="span2" style="margin-top: 20px;"><input type="submit" value="Bắt đầu thi" id="start"/></div>-->
            <div class="span2" style="margin-top: 20px;" id="start">
                <a>Bắt đầu thi</a> 
            </div>
        </div>
    </div>

</form>

<script type="text/javascript">

    jQuery(function ($) {
        $("#start").click(function () {
            if ($("#nganh_nghe_id").val() == '0') {
                alert('Vui lòng chọn ngành nghề');
                $("#nganh_nghe_id").focus();
                return;
            }
            if ($("#level").val() == '0') {
                alert('Vui lòng chọn cấp bậc');
                $("#level").focus();
                return;
            }
            $("#form1").attr('onsubmit', 'return true');
            $("#form1").submit();
        });
        $("#nganh_nghe_id").val('<?php echo $this->nganhNgheId; ?>');
        $("#level").val('<?php echo $this->level; ?>');

    });


</script>
