<?php

$nganhnghe_ids = $this->nganhnghe_ids;
if (isset($this->message)&&trim($this->message)!='') {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3"></div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $this->message;
            ?>
        </div>
        <div class="span3"></div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="margin-top: 10px;">
    <?php     
    $buttons[]=array('onclick'=>"window.location = '".$this->baseUrl('/admin/question/index/page/'.$this->page)."'",'label'=>'Quay lại');
    $buttons[]=array('onclick'=>'document.form.submit();','label'=>'Lưu');
    echo $this->toolbar($buttons);
    ?>
</div>
<form name="form" enctype="multipart/form-data" id="form" action="<?php echo $this->url(); ?>" method="post">
    <div class="row-fluid" style="margin-top: 10px;">
        <div class="span4"></div>

        <div class="span12">
            <?php echo $this->form($this, $this->form, 1, $echo_form_tag = FALSE); ?>
        </div>

    </div>

    <div class="row-fluid" style="margin-top: 10px;">



        <?php
        if (is_numeric($this->form->getElement('id')->getValue())) {
            $mapper = new \Application\Model\Answer();
            $menus = $mapper->select('*')->where("question_id=" . $this->form->getElement('id')->getValue())->order('sign')->fetchAll();
            $dap_an = isset($this->dap_an) ? $this->dap_an : Core_Db_Table::getDefaultAdapter()->query('select answer_id from dap_an where question_id=' . $this->form->getElement('id')->getValue())->fetchColumn();
            if (is_array($menus) && count($menus) > 0) {
                ?>
                <h3 style="text-align: center;">Chọn đáp án</h3>

                <?php
                foreach ($menus as $menu) {
                    ?>
                    <div>

                        <label>

                            <input type="radio" name="dap_an" value="<?php echo $menu['id'] . '_' . $menu['sign']; ?>"<?php if ($dap_an == $menu['id']) { ?> checked<?php } ?>/>
                            <?php
                            echo $menu['sign'] . ' ' . $menu['content'];
                            ?>
                        </label>

                    </div>    
                    <?php
                }
                ?>

                <?php
            }
        }
        ?>
    </div>    

    <div class="row-fluid" style="margin-top: 10px;">



        <?php
        if ($this->form->getElement('question_id') == null) {
            $mapper = new \Application\Model\Nganhnghe();
            $menus = $mapper->getNganhNghes();
            if (is_array($menus) && count($menus) > 0) {
                ?>
                <h3 style="text-align: center;">Chọn ngành nghề</h3>

                <?php foreach ($menus as $menu) { ?>
                    <div style="margin-left: 50px;">

                        <label>

                            <input type="checkbox" name="nganhnghe_id[]" value="<?php echo $menu['id']; ?>"<?php if (in_array($menu['id'], $nganhnghe_ids)) { ?> checked<?php } ?>/>
                            <?php
                            echo $menu['title'];
                            ?>
                        </label>

                    </div>    



                    <?php
                }
            }
        }
        ?>
    </div>    


</form>    

<script type="text/javascript">
    jQuery(function ($) {


        $("form").find("textarea").eq(0).focus();

    });

</script>



