<?php
$items = $this->items;



$session = new \Zend\Session\Container('base');
if ($session->offsetExists('user')) {
    $identity = $session->offsetGet('user');
}


?>
<script type="text/javascript">
    function editItem(img) {
        jQuery("form#edit-form").find('input[type="hidden"]').eq(0).val(jQuery(img).parent().parent().attr("id")).attr("name", "id");
        jQuery("form#edit-form").submit();

    }
    jQuery(function ($) {
        $(".parent").click(function () {
            if ($(this).attr('src').indexOf('down') != -1) {
                src = $(this).attr('src');
                src = src.replace('down', 'up');
            } else {
                src = src.replace('up', 'down');
            }

            $(this).attr('src', src);
            $(this).parent().parent().next().slideToggle();
        });
    });

</script>
<?php

if (isset($this->message)&&trim($this->message)!='') {
    ?>
    <div class="row-fluid" style="margin-top: 20px;">
        <div class="span3"></div>
        <div class="span6" align='center' style='color: red;'>
            <?php
            echo $this->message;
            ?>
        </div>
        <div class="span3"></div>
    </div>
    <?php
}
?>
<div class="row-fluid" style="padding-top:20px;">

    <div class="span12">
        <?php     
        $buttons[]=array('onclick'=>"window.location = '".$this->basePath('/admin/question/add/page/'.$this->page)."'",'label'=>'Thêm câu hỏi');
        echo $this->toolbar($buttons);
        ?>
    </div>
</div>

<div class="row-fluid">

    <?php
    $background='';
    foreach ($items as $item) {
        if($background=='silver'){
            $background='white';
        }
        else{
            $background='silver';
        }

        $item_des = $item['content'];
        ?>

        <div style="background-color: <?php echo $background;?>" class="row-fluid" id="<?php echo $item['id']; ?>">
            <div class="span1" title="Thêm mới câu trả lời">
                <a href="<?php echo $this->basePath('/admin/question/addanswer/question_id/') . $item['id'].'/page/'.$this->page; ?>">
                    <img style="width: 43px;height: 41px;" src="<?php echo $this->basePath("/images/icon/add.gif"); ?>"/>
                </a>
            </div>
            <div class="span8">
                <?php echo $item_des; ?>
            </div>
            <div class="span2">
                <a class="remove" title="Click vào đây để xóa" href="<?php echo $this->basePath('/admin/question/delete/question_id/') . $item['id']; ?>">
                    <img class="delete question" src="<?php echo $this->basePath("/images/icon/delete-icon.png"); ?>"/>                                                   
                </a>

                <a href="<?php echo $this->basePath('/admin/question/edit/id/') . $item['id'].'/page/'.$this->page; ?>">
                    <img class="edit question" title="Click vào đây để sửa" style="cursor: pointer;" src="<?php echo $this->basePath("/images/icon/ico_edit.png"); ?>" onclick="editItem(this);"/>                                                   
                </a>
            </div>
            <div class="span1" style="margin: 0 auto;text-align: center;display: table-cell;vertical-align: middle;">
                <?php if (count($item['answers']) > 0) { ?>
                    <img class="parent" src="<?php echo $this->basePath(); ?>/images/down.png" style="width: 32px;height: 32px;cursor: pointer;"/>
                    <?php
                }
                ?>
            </div>
        </div>

        <div class="row-fluid" style="display: none;background-color: blue;color: white;">

    <?php
    $answers = $item['answers'];
    foreach ($answers as $answer) {
        $item_des = $answer['content'];
        ?>
                <div class="row-fluid" style="border-bottom: dotted black 1px;border-right: solid 1px black;">
                    <div class="span1">

                    </div>
                    <div class="span1" style="border-right: solid 1px black;">
        <?php echo $answer['sign']; ?>
                    </div>
                    <div class="span8" style="border-right: solid 1px black;">
                        <?php echo $item_des; ?>
                    </div>
                    <div class="span2" style="border-right: solid 1px black;">
                        <a class="remove" title="Click vào đây để xóa" href="<?php echo $this->basePath('/admin/question/delete/answer_id/') . $answer['id']; ?>">
                            <img class="delete answer" src="<?php echo $this->basePath("/images/icon/delete-icon.png"); ?>"/>                                                   
                        </a>

                        <a href="<?php echo $this->basePath('/admin/question/editanswer/id/') . $answer['id'].'/page/'.$this->page; ?>">
                            <img class="edit answer" title="Click vào đây để sửa" style="cursor: pointer;" src="<?php echo $this->basePath("/images/icon/ico_edit.png"); ?>" onclick="editItem(this);"/>                                                   
                        </a>
                    </div>

                </div>
        <?php
    }
    ?>

        </div>


    <?php
}
$url = $this->url();
$temp = explode('page', $url);
if (is_array($temp) && count($temp) == 2) {
    $url = $temp[0];
}
?>

</div>
<form method="post" action="<?php echo $url; ?>">
    <div class="row-fluid">
        <div class="span12">
<?php if ($this->total > $this->limit) { ?>
                <table style="width: 100%;">
                    <tfoot>
                        <tr>
                            <td colspan="3" style="width: 100%;"><?php echo $this->paginationControl($this->paginator, 'Sliding', array('_partials/paginator.phtml', 'default')); ?></td>
                        </tr>
                    </tfoot>
                </table>
    <?php
}
?>
        </div>
    </div>
</form>

